export const ExperienceData = [{
        id: "bwi",
        role: "React Developer",
        name: "Build with Innovation",
        link: "https://drive.google.com/file/d/1FZ0fDpvy9Um3f_jzK5ga27ngkIcoevQH/view?usp=sharing",
        duration: "Dec 2020 - May 2021",
        type: "Internship",
        description: "- Worked together with the core team to design and code client applications using React, Material UI, and Firebase.  \n - Single-handedly developed BWI-website-builder for getting paid web development orders from clients around the world using React, Material UI, Firebase, and Razorpay. \n - Initiated the development of an eShopping fullstack template for deploying fully managable eShopping websites for clients, using React, Redux, and Firebase.",
    },
    {
        id: "parva",
        role: "React Developer",
        name: "Parva",
        link: "https://drive.google.com/file/d/1sTwfiEHi7G5prtnPZdkrMwCwUEGdnrhc/view?usp=sharing",
        duration: "Dec 2020 - Feb 2021",
        type: "Internship",
        description: "- Collaborated with other developers to drive the development of Parva's social platform for communities.  \n - Refactored the original codebase to improve code readability and responsiveness of the platform.  \n - Added new social features, comments and likes, for events and blogs.",
    },
    {
        id: "ieee",
        role: "Design/Backend Mentor, Web/App Domain",
        name: "IEEE, SRMIST",
        link: "https://drive.google.com/file/d/1L-i4YllGKbJWGSLaIpTOUgU9qY_TXQ5n/view?usp=sharing",
        duration: "Dec 2020 - Present",
        type: "College Club",
        description: "- Got promoted from Tech Lead in July, 2021. \n - Collaborated with other leads and heads to make in-house projects for college and third-party clients. \n - Mentoring and guiding juniors in frontend development and UI/UX design. \n - Enhanced the looks and experience of several IEEESRMIST webapps including [register.ieeesrmist.in](https://register.ieeesrmist.in/) and [ieeesrmist.in](https://ieeesrmist.in) .",
    },
    {
        id: "td",
        role: "Web Dev Member",
        name: "Think-Digital, SRMIST",
        link: null,
        duration: "Sep 2020 - Present",
        type: "College Club",
        description: "- Worked on personal projects including [Twitter clone](https://github.com/AyushiPrakash/Twitter-Clone) . \n - Learnt about backend development with Nodejs and Express.",
    },
];