export const SkillSet = [
  {
    name: "Twitter Clone",
    description: "",
    image: "/assets/projects/twitter-clone.png",
    tools: "",
    githubLink: "",
    demoLink: "",
  },
  {
    name: "BWI Website Builder",
    description: "",
    image: "/assets/projects/bwi-wb.png",
    tools: "",
    githubLink: "",
    demoLink: "",
  },
  {
    name: "Misty, A weather app",
    description: "",
    image: "/assets/projects/misty.png",
    tools: "",
    githubLink: "",
    demoLink: "",
  },
  {
    name: "Life Checklist",
    description: "",
    image: "/assets/projects/life-checklist.png",
    tools: "",
    githubLink: "",
    demoLink: "",
  },
  {
    name: "Bulletin Board",
    description: "",
    image: "/assets/projects/bulletin-board.png",
    tools: "",
    githubLink: "",
    demoLink: "",
  },
  {
    name: "Calculator",
    description: "",
    image: "/assets/projects/calculator.png",
    tools: "",
    githubLink: "",
    demoLink: "",
  },
  {
    name: "To-do List",
    description: "",
    image: "/assets/projects/to-do-list.png",
    tools: "",
    githubLink: "",
    demoLink: "",
  },
];
