export const projects = [
  {
    name: "Twitter Clone",
    description: "A functional Twitter Clone with Auth System and CRUD API.",
    image: "/assets/projects/twitter-clone.png",
    tools: [Javascript, Expressjs, CSS , EJS, SQL],
    githubLink: "https://github.com/AyushiPrakash/Twitter-Clone",
    demoLink: "",
    isFeatured: true,
  },
  {
    name: "BWI Website Builder",
    description: "",
    image: "/assets/projects/bwi-wb.png",
    tools: [React , Firebase ,Axios ,MaterialUI],
    githubLink: "",
    demoLink: "https://bwi-website-builder.web.app/",
    isFeatured: true,
  },
  {
    name: "Misty, A weather app",
    description: "Get the current weather for any location on the fly.",
    image: "/assets/projects/misty.png",
    tools: [React , Axios],
    githubLink: "https://github.com/AyushiPrakash/Misty",
    demoLink: "https://misty.vercel.app/",
    isFeatured: true,
  },
  {
    name: "Life Checklist",
    description: "",
    image: "/assets/projects/life-checklist.png",
    tools: [React, SASS],
    githubLink: "https://github.com/AyushiPrakash/Life-Checklist",
    demoLink: "https://lifechecklist.vercel.app/",
  },
  {
    name: "Bulletin Board",
    description: "A simple app to write anything on the board.",
    image: "/assets/projects/bulletin-board.png",
    tools: [React],
    githubLink: "https://github.com/AyushiPrakash/Bulletin-Board",
    demoLink: "https://pinboard-jn2cadotw.vercel.app/",
  },
  {
    name: "Calculator",
    description:
      "A simple calculator using Html, CSS and JS with dark mode and responsive design.",
    image: "/assets/projects/calculator.png",
    tools: [HTML, CSS, Javascript],
    githubLink: "https://github.com/AyushiPrakash/Calculator",
    demoLink: "https://ayushiprakash.github.io/Calculator/",
  },
  {
    name: "To-do List",
    description:
      "Just another To-do list™ made using vanilla-javascript with add, delete and search features.",
    image: "/assets/projects/to-do-list.png",
    tools: [HTML, CSS, Javascript],
    githubLink: "https://github.com/AyushiPrakash/TO-DO-List",
    demoLink: "https://ayushiprakash.github.io/TO-DO-List/",
  },
];
