export const ProjectsData = [{
        name: "BWI Website Builder ",
        description: "- A website for getting paid web development orders from clients around the world.  \n",
        tools: ["React", "Firebase", "Axios", "MaterialUI"],
        githubLink: null,
        demoLink: "https://bwi-website-builder.web.app/",
    },
    {
        name: "Twitter Clone",
        description: "A functional Twitter Clone with Auth System and CRUD API.",
        tools: ["Javascript", "Expressjs", "CSS", "EJS", "SQL"],
        githubLink: "https://github.com/AyushiPrakash/Twitter-Clone",
        demoLink: null,
    },

    {
        name: "Misty, A weather app",
        description: "Get the current weather for any location on the fly.",
        tools: ["React", "Axios"],
        githubLink: "https://github.com/AyushiPrakash/Misty",
        demoLink: "https://misty.vercel.app/",
    },
    {
        name: "Life Checklist",
        description: null,
        tools: ["React", "SASS"],
        githubLink: "https://github.com/AyushiPrakash/Life-Checklist",
        demoLink: "https://lifechecklist.vercel.app/",
    },
    {
        name: "Bulletin Board",
        description: "A simple app to write anything on the board.",
        tools: ["React"],
        githubLink: "https://github.com/AyushiPrakash/Bulletin-Board",
        demoLink: "https://pinboard-jn2cadotw.vercel.app/",
    },
    {
        name: "To-do List",
        description: "Just another To-do list™ made using vanilla-javascript with add, delete and search features.",
        tools: ["HTML", "CSS", "Javascript"],
        githubLink: "https://github.com/AyushiPrakash/TO-DO-List",
        demoLink: "https://ayushiprakash.github.io/TO-DO-List/",
    },
    {
        name: "BWI Website Builder ",
        description: "- A website for getting paid web development orders from clients around the world.  \n",
        tools: ["React", "Firebase", "Axios", "MaterialUI"],
        githubLink: null,
        demoLink: "https://bwi-website-builder.web.app/",
    },
    {
        name: "Twitter Clone",
        description: "A functional Twitter Clone with Auth System and CRUD API.",
        tools: ["Javascript", "Expressjs", "CSS", "EJS", "SQL"],
        githubLink: "https://github.com/AyushiPrakash/Twitter-Clone",
        demoLink: null,
    },

    {
        name: "Misty, A weather app",
        description: "Get the current weather for any location on the fly.",
        tools: ["React", "Axios"],
        githubLink: "https://github.com/AyushiPrakash/Misty",
        demoLink: "https://misty.vercel.app/",
    },
    {
        name: "Life Checklist",
        description: null,
        tools: ["React", "SASS"],
        githubLink: "https://github.com/AyushiPrakash/Life-Checklist",
        demoLink: "https://lifechecklist.vercel.app/",
    },
    {
        name: "Bulletin Board",
        description: "A simple app to write anything on the board.",
        tools: ["React"],
        githubLink: "https://github.com/AyushiPrakash/Bulletin-Board",
        demoLink: "https://pinboard-jn2cadotw.vercel.app/",
    },
    {
        name: "To-do List",
        description: "Just another To-do list™ made using vanilla-javascript with add, delete and search features.",
        tools: ["HTML", "CSS", "Javascript"],
        githubLink: "https://github.com/AyushiPrakash/TO-DO-List",
        demoLink: "https://ayushiprakash.github.io/TO-DO-List/",
    },
];